# =========================
# ETAPA 1: COMPILACIÓN
# =========================
FROM maven:3.9.6-eclipse-temurin-25 AS build

WORKDIR /app

# Copiar el pom.xml y descargar dependencias
COPY pom.xml .
RUN mvn dependency:go-offline

# Copiar el código fuente
COPY src ./src

# Compilar sin tests
RUN mvn clean package -DskipTests


# =========================
# ETAPA 2: EJECUCIÓN
# =========================
FROM eclipse-temurin:25-jre

WORKDIR /app

# Copiamos el jar final (de Spring Boot será uno único y ejecutable)
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
