# =========================
# ETAPA 1: COMPILACIÓN
# =========================
FROM maven:3.9.11-eclipse-temurin-25 AS build

WORKDIR /app

# Copiamos primero el POM para descargar dependencias
COPY pom.xml .
RUN mvn dependency:go-offline

# Copiamos el código fuente
COPY src ./src

# Compilamos el proyecto
RUN mvn clean package -DskipTests


# =========================
# ETAPA 2: EJECUCIÓN
# =========================
FROM eclipse-temurin:25-jre

WORKDIR /app

# Copiamos el JAR generado
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

# Ejecutamos la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]